robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 5

  # Position Controllers ---------------------------------------
  pan_tilt_position_controller:
    type: effort_controllers/JointEffortController
    joint: base_to_pan_tilt
    pid: {p: 100.0, i: 0.01, d: 10.0}
